# Generated by Django 5.1.4 on 2024-12-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AddField(
            model_name='category',
            name='description_template',
            field=models.TextField(default='Description template for {category} category.'),
        ),
    ]
