# Generated by Django 5.1.4 on 2024-12-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_employer',
            field=models.BooleanField(default=False),
        ),
    ]
